import React from 'react';
import SEO from '../components/SEO';
import { Link } from 'react-router-dom';

const Disclaimer: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:py-16 lg:px-8">
      <SEO 
        title="Medical & Legal Disclaimer | AdvocaMed" 
        description="Review our medical and legal disclaimer. AdvocaMed provides administrative billing assistance, not professional medical advice."
        canonical="/disclaimer"
      />
      
      <div className="bg-white dark:bg-surface-dark rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800 p-8 sm:p-12">
        <h1 className="text-3xl font-bold text-text-main-light dark:text-text-main-dark mb-6">Medical & Legal Disclaimer</h1>
        <p className="text-sm text-text-secondary-light dark:text-text-secondary-dark mb-8">
          Last Updated: April 28, 2026
        </p>

        <div className="prose prose-blue dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white border-b pb-2 mb-4">1. No Medical Advice</h2>
            <p className="font-semibold text-red-600 dark:text-red-400 mb-2">
              The information provided on this site cannot replace professional medical diagnosis, treatment, or advice.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              AdvocaMed.ai operates exclusively as a financial/administrative advocacy platform. The content on our website,
              our blog posts, and the output of our AI tools are intended solely for educational and informational purposes
              regarding the financial and administrative aspects of US healthcare billing.
            </p>
            <p className="text-gray-700 dark:text-gray-300 mt-2">
              Always seek the advice of your physician or other qualified healthcare provider regarding any medical
              condition. Do not disregard professional medical advice or delay seeking it because of something you have
              read on this website. In a medical emergency, call 911 or visit the nearest emergency room immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white border-b pb-2 mb-4">2. No Legal or Financial Advice</h2>
            <p className="text-gray-700 dark:text-gray-300">
              We are not a law firm, accounting firm, or insurance provider. While we strive to provide accurate analyses
              based on CMS data and federal regulations (like IRS Section 501(r)), our services do not constitute reliable
              legal advice. The calculations, templates, and dispute letters provided by our platform are examples.
              Consult with a dedicated patient advocate or attorney for complex disputes or debt collection scenarios.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white border-b pb-2 mb-4">3. AI Analysis Limitations</h2>
            <p className="text-gray-700 dark:text-gray-300">
              The AdvocaMed audit engine analyzes scanned bills comparing them against external data sources. The resulting
              "savings," "detected errors," and "upcoded alerts" are estimates generated by an automated algorithm.
              They are not guaranteed outcomes and must be validated through official hospital channels.
            </p>
          </section>

          <div className="mt-12 bg-gray-50 dark:bg-gray-800/50 p-6 rounded-xl">
            <p className="text-sm text-gray-600 dark:text-gray-400 text-center">
              By using AdvocaMed, you signify your acceptance of this disclaimer. For further details on how we handle
              your data, please refer to our <Link to="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link> and <Link to="/terms" className="text-primary hover:underline">Terms of Service</Link>.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
